{% set name = "stonesoup" %}
{% set version = "0.1b11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34f8bf726454023be9b455943ee5705f17c2216320473f2e03552d83181a9d5c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools-scm >=7
  run:
    - python >=3.7
    - matplotlib-base
    - numpy >=1.17
    - pymap3d
    - ruamel.yaml >=0.16.5
    - scipy
    - setuptools >=45
    - utm
    - rtree
    - ordered-set

test:
  imports:
    - stonesoup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dstl/Stone-Soup
  license: MIT
  license_file: LICENSE
  summary: 'A tracking and state estimation framework'
  description: |
    Stone Soup is a software project to provide the target tracking and
    state estimation community with a framework for the development and
    testing of tracking and state estimation algorithms.
  doc_url: https://stonesoup.rtfd.io/en/v{{ version }}/
  dev_url: https://github.com/dstl/Stone-Soup

extra:
  recipe-maintainers:
    - sdhiscocks
