{% set name = "stonesoup" %}
{% set version = "1.7" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ada4d9d2500c3368752fe85ce7f73dc28b90188f7b01346468bf2b94e4f82d5f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm >=8
    - setuptools >=64
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy >=1.17
    - ordered-set
    - plotly
    - pymap3d
    - rtree
    - ruamel.yaml >=0.16.5
    - scipy
    - utm

test:
  imports:
    - stonesoup
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/dstl/Stone-Soup
  license: MIT
  license_file: LICENSE
  summary: 'A tracking and state estimation framework'
  description: |
    Stone Soup is a software project to provide the target tracking and
    state estimation community with a framework for the development and
    testing of tracking and state estimation algorithms.
  doc_url: https://stonesoup.rtfd.io/en/stable/
  dev_url: https://github.com/dstl/Stone-Soup

extra:
  recipe-maintainers:
    - csherman-dstl
    - nperree-dstl
    - sdhiscocks
