{% set name = "stonesoup" %}
{% set version = "1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23e2445f49868dd6c04b02ba4faecd8eb56026799538973f31e45bc9a5a73e61

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm >=8
    - setuptools >=64
  run:
    - python >=3.8
    - matplotlib-base
    - mergedeep
    - numpy >=1.17
    - pymap3d
    - ruamel.yaml >=0.16.5
    - scipy
    - utm
    - rtree
    - ordered-set

test:
  imports:
    - stonesoup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dstl/Stone-Soup
  license: MIT
  license_file: LICENSE
  summary: 'A tracking and state estimation framework'
  description: |
    Stone Soup is a software project to provide the target tracking and
    state estimation community with a framework for the development and
    testing of tracking and state estimation algorithms.
  doc_url: https://stonesoup.rtfd.io/en/v{{ version }}/
  dev_url: https://github.com/dstl/Stone-Soup

extra:
  recipe-maintainers:
    - nperree-dstl
    - sdhiscocks
